name: Continuous Integration

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Installing dependencies
      run: yarn
    - name: Running Type Check
      run: yarn type-check
    - name: Running Linter
      run: yarn lint
    - name: Running Prettier Format
      run: yarn format